### ISSUE TITLE
IndexOutOfBoundsException on clicking back after importing a file

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1331]
_From @steveswinsburg on March 12, 2015 20:30_

When you import a file and go to next screen, then click back, an IndexOutOfBoundsException is thrown:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
     at java.util.ArrayList.rangeCheck(ArrayList.java:635)
     at java.util.ArrayList.get(ArrayList.java:411)
     at org.sakaiproject.gradebookng.tool.panels.importExport.CreateGradeItemStep.<init>(CreateGradeItemStep.java:71)
     at org.sakaiproject.gradebookng.tool.panels.importExport.GradeItemImportSelectionStep$1.onSubmit(GradeItemImportSelectionStep.java:62)
     at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1294)
     at org.apache.wicket.markup.html.form.Form.process(Form.java:952)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:784)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:717)
     at java.lang.reflect.Method.invoke(Method.java:606)

_Copied from original issue: steveswinsburg/gradebookNG#12_

**Comment by steveswinsburg** [comment]
_From @maurercw on March 17, 2015 1:40_

Can you give any additional steps to reproduce?  I'm not able to reproduce in my local version (my forked branch).

**Comment by steveswinsburg** [comment]
_From @maurercw on March 17, 2015 1:49_

That's weird...I am getting totally different results between firefox and chrome.  Hitting back in FF still seems to progress forwards while chrome works as expected.

**Comment by steveswinsburg** [comment]
Maybe that is it, FF is going forwards.

To reproduce in FF, download the full gradebook, then upload it without modification. On the next screen click Back, boom.

**Comment by steveswinsburg** [comment]
I think the issue is that its a submit button so wicket will submit the form. You probably want to handle this as a normal button (like a cancel) with setDefaultFormProcessing to false so it doesnt submit.

**Comment by steveswinsburg** [comment]
_From @maurercw on March 17, 2015 12:57_

I updated the pull request last night (my last night, so about 10 hours ago!) with a change.  I didn't set setDefaultFormProcessing, but did turn them into buttons.  Apparently I had some that were still submits and some that were already buttons.

**Comment by steveswinsburg** [comment]
_From @maurercw on March 25, 2015 3:3_

I'm hoping that this issue has been addressed now?

**Comment by steveswinsburg** [comment]
Which branch did you commit against? I cant see any commits on this PR. If you commit to the same branch that the PR was for, then push, git will link it up. I can see the commit on your master, looks like you might just need to send me another PR.

The other thing you might want to do is work in a branch then you can just send a PR for the whole branch.

Are you using Sourcetree? Makes life a lot easier :)

**Comment by steveswinsburg** [comment]
_From @maurercw on March 25, 2015 13:9_

PR #6 is the one that would have had all this stuff in it.  I also just did a small one this morning (PR #27) for the import success message.  I'll switch to work in a branch from here on and see if that makes things any easier.

**Comment by steveswinsburg** [comment]
Ok I don't see any new commits on that one either.
https://github.com/steveswinsburg/gradebookNG/pull/6

Hmm. You can probably just send a PR for the entire master and it should
pickup any commits that havent been merged.

**Comment by steveswinsburg** [comment]
_From @maurercw on March 25, 2015 20:27_

It wasn't a rebase, just a merge, so you'll have my commits sprinkled
throughout your master commits.
Some of that was before I knew how to use git as well!
We've been using it for a while on our project at IU, so I've gotten
better!  We're using some git flow tools too.
I'll look through your stuff to verify if all of my stuff is there or not...

Chris

**Comment by steveswinsburg** [comment]
Ok great. I'll give it a run through tonight and check too.

**Comment by steveswinsburg** [comment]
Ok this seems to be working ok, however does break with the introduction of the new request mapper:
https://github.com/steveswinsburg/gradebookNG/issues/35

I think the history.back is the issue, can you do that via Wicket? (setResponsePage)

**Comment by steveswinsburg** [comment]
_From @maurercw on April 2, 2015 2:53_

PR #37 has some changes for the back button.  Let me know if that works out for you.  The constructors for my import panel classes are getting pretty messy...  I may look into using some sort of model to wrap up all the stuff I'm passing around.

**Comment by steveswinsburg** [comment]
_From @maurercw on April 2, 2015 3:27_

PR #37 updated with some model stuff now.  May not be the best approach yet, but hopefully cleaner.

**Comment by steveswinsburg** [comment]
Have a look at what I'm doing for the student name panels. Basically
passing in a model which wraps a map of data, then unpack the model in the
onInitialise method (not the constructor). Migrating my stuff over to use
that approach, seems to work pretty well, just need to document the model
object map fields for each panel so ppl know what's in there :)

**Comment by steveswinsburg** [comment]
_From @maurercw on April 3, 2015 4:52_

Cleaned up the models some more in PR #40.  Let me know if I'm getting closer!

**Comment by steveswinsburg** [comment]
Ok I'm closing this one off, we can raise separate issues as required.
