### ISSUE TITLE
Reorder not sticking

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1373]
_From @kyleblythe on November 19, 2015 19:1_

As per last week's GB call, drag-and-drop does not appear to save in either grouped or ungrouped mode. Reordering via the drop-down menu does not appear to save either; resetting the tool reverts the items to their previous position.

Regardless of what category the items belong to, the console debugging panel reports a 500 (internal server error):

![image](https://cloud.githubusercontent.com/assets/11447474/11280841/df659ad0-8ec5-11e5-8fef-1e31ef2e9eff.png)

Example site: https://sandboxclasses1.home.nyu.edu/portal/site/0866a09a-9673-4d31-8a2c-e8a9f2c0b1dd/tool/4fe51b5b-75b4-4a13-960a-1a421445aeaa

Item: any (though I tried to reorder "Homework 3" at 1:59pm 

_Copied from original issue: steveswinsburg/gradebookNG#282_

**Comment by steveswinsburg** [comment]
_From @payten on November 19, 2015 20:24_

When drag-moving a Participation category grade item I hit this exception:
```
Full stacktrace:
RuntimeException:Fatal error trying to execute custom action method: categorized-assignment-order:new:updateCategorizedAssignmentOrder:
java.lang.RuntimeException: Fatal error trying to execute custom action method: categorized-assignment-order:new:updateCategorizedAssignmentOrder
	at org.sakaiproject.entitybroker.rest.EntityActionsManager.handleCustomActionExecution(EntityActionsManager.java:231)
	at org.sakaiproject.entitybroker.rest.EntityActionsManager.handleCustomActionRequest(EntityActionsManager.java:96)
	at org.sakaiproject.entitybroker.rest.EntityHandlerImpl.handleEntityAccess(EntityHandlerImpl.java:405)
	at org.sakaiproject.entitybroker.util.servlet.DirectServlet.dispatch(DirectServlet.java:183)
	at org.sakaiproject.entitybroker.servlet.SakaiDirectServlet.dispatch(SakaiDirectServlet.java:146)
	at org.sakaiproject.entitybroker.util.servlet.DirectServlet.handleRequest(DirectServlet.java:154)
	at org.sakaiproject.entitybroker.util.servlet.DirectServlet.service(DirectServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.oauth.filter.OAuthPostFilter.doFilter(OAuthPostFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:467)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.oauth.filter.OAuthPreFilter.doFilter(OAuthPreFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sakaiproject.entitybroker.rest.EntityActionsManager.handleCustomActionExecution(EntityActionsManager.java:206)
	... 37 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.updateCategorizedAssignmentOrder(GradebookNgBusinessService.java:1063)
	at org.sakaiproject.gradebookng.rest.GradebookNgEntityProvider.updateCategorizedAssignmentOrder(GradebookNgEntityProvider.java:172)
	... 42 more
```

**Comment by steveswinsburg** [comment]
_From @payten on November 30, 2015 4:1_

While I've delivered for the issue you raised @kyleblythe, I worry that there are cases where the XML used to store the categorized sort order could become out of sync with the state of the gradebook. I've created a new task for @steveswinsburg and I to look into refactoring this feature in an effort to make it more robust #285.
