### ISSUE TITLE
Section Awareness for "Set Score for Empty Cells," with persistent confirmation message

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1376]
_From @kyleblythe on September 11, 2015 13:52_

Provide section awareness for the "Set Score for Empty Cells" functionality in GB items, allowing for scores to be applied to empty cells on a section-by-section (or group-by-group) basis. A new drop-down menu within the "Set Score for Empty Cells" lightbox will allow for instructors/TAs to choose the section/group for which to apply scores (with, in the case of TAs, this being restricted by the sections/groups for which they have grade access).

A new confirmation message will appear any time a score is set, notifying users of the score that is being applied and what section(s)/group(s) to which the score is being applied.

For Instructors:
* When viewing the Gradebook by All Sections/Groups, selecting "Set Score for Empty Cells" will open the lightbox. The drop-down within will be set, by default, to "All Sections/Groups."
* When filtering by a given section/group, selecting "Set Score for Empty Cells" will open the lightbox. The drop-down within will be set, by default, to the section/group by which they are currently filtering. This can be modified by selecting the drop-down.

For TAs:
"Set Score for Empty Cells" will be restricted only to sections/groups for which the TA has "Grade" permissions. If they have "grade" access for multiple sections/groups, apply the same capabilities as above.

_Copied from original issue: steveswinsburg/gradebookNG#226_

**Comment by payten** [comment]
When TA doesn't have EDIT access to the all sections, this exception is thrown when the set score action is submitted:
```
java.lang.SecurityException: User 159f93ad-5e14-485a-adf7-e06e07e835c9 attempted to save a grade for 0b20f0b9-4c17-43f7-bd5d-9d7f480b9f47 without authorization
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.saveGradesAndComments(GradebookServiceHibernateImpl.java:2120)
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.saveGradeAndCommentForStudent(GradebookServiceHibernateImpl.java:2014)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy47.saveGradeAndCommentForStudent(Unknown Source)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.updateUngradedItems(GradebookNgBusinessService.java:1348)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$8d9885ac.updateUngradedItems(<generated>)
	at org.sakaiproject.gradebookng.tool.panels.UpdateUngradedItemsPanel$1.onSubmit(UpdateUngradedItemsPanel.java:84)
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:108)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$1.onSubmit(AjaxFormSubmitBehavior.java:182)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1288)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:952)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:784)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:159)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:124)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:250)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:410)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1482)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:478)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:271)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:152)
	at org.sakaiproject.portal.charon.handlers.WorksiteHandler.doPost(WorksiteHandler.java:71)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doPost(SkinnableCharonPortal.java:1135)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:471)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by raulsv** [comment]
That issue should take into account the 'Set Zero Score For Empty Cells' option. This option should be the section awareness too.

![setzero](https://cloud.githubusercontent.com/assets/10761548/13492507/c61303a4-e138-11e5-9648-a46c9f27a106.png)

**Comment by steveswinsburg** [comment]
Discussed 1/4/2016:
First comment still holds regarding section awareness and dropdowns in individual gradebook items.
Future enhancement may be that we implement this for the 'set zero score for empty cells' option as well (however it would still be a zeroing action).

**Comment by raulsv** [comment]
Hi Steve

I've created a new issue for this enhancement: https://github.com/sakaiproject/sakai/issues/2113. Regards,

Raúl

**Comment by kyleblythe** [comment]
@steveswinsburg ,

This is working _beautifully_. Love it! From the instructor's perspective especially, this is functioning perfectly. Thanks!

I am noticing something from the TA's perspective though. To replicate:

1. Give a TA grading access to a single section/group for any category.
2. Provide viewing access to another section/group for the same category
2. Become the TA and select the "Set Score for Empty Cells" option.

Since the "Set Score" window matches filtering that's currently happening in the section/group dropdown (which should definitely be the case, at least from the instructor's perspective), the Set Score defaults to "All Sections/Groups" for the TA:

![image](https://cloud.githubusercontent.com/assets/11447474/14288193/b2b48db4-fb23-11e5-89d0-20943de6a884.png)

However, the TA doesn't have grading access for all sections/groups. So when they try to submit a score, they get the following error:

![image](https://cloud.githubusercontent.com/assets/11447474/14288182/a84b0222-fb23-11e5-8bd3-35f22485488f.png)

So, for TA's at least, I think this Set Score for Empty Cells should look to the TA's grading Permissions. Since, in this case, they only have grading permissions for a single section, then there shouldn't be a dropdown - it should just default to the grade-able section. Does that make sense?

I also made a comment in #1366 around the naming used in the section/group dropdown. If a TA has access to multiple sections/groups but not **all** sections/groups, then the dropdown should probably reflect that. And if the TA only has access to a single section/group in the GB, then there probably shouldn't be a dropdown filter at all.

Sorry to complicate this! The section awareness for the "Set Score" is looking awesome!

**Comment by steveswinsburg** [comment]
This was actually @payten's delectable work. I can fix this behaviour though, just let me know P.

**Comment by kyleblythe** [comment]
Fantastic! This is working fantastically. Confirmed.
