### ISSUE TITLE
Calculating percentage for new category throws NPE

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1436]
In the category percentage calculation code, if there are no categories and a new one is added, some fields will be null and the percentage calculation will throw an NPE.

````
Caused by: java.lang.NullPointerException
	at org.sakaiproject.gradebookng.tool.panels.SettingsCategoryPanel.calculateCategoryWeightTotal(SettingsCategoryPanel.java:271)
	at org.sakaiproject.gradebookng.tool.panels.SettingsCategoryPanel.access$000(SettingsCategoryPanel.java:32)
	at org.sakaiproject.gradebookng.tool.panels.SettingsCategoryPanel$4$1.onUpdate(SettingsCategoryPanel.java:171)
	at org.apache.wicket.ajax.form.AjaxFormComponentUpdatingBehavior.onEvent(AjaxFormComponentUpdatingBehavior.java:153)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:124)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
````

**Comment by steveswinsburg** [comment]
Fixed
