### ISSUE TITLE
Error when updating uncategorized GB items or when uncategorizing a currently categorized item

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1751]
"An error occurred updated the gradebook item" error message appears when attempting to do the following:

* un-categorize a currently categorized item. Refreshing/resetting the tool shows that the action has not successfully completed.

* update a currently uncategorized item. However, refreshing/resetting the tool show that the action has been successfully completed.

http://www.screencast.com/t/gto9xlYTO

Stacktrace error:

`2016-02-19 08:03:40,385 ERROR http-nio-8080-exec-12 org.sakaiproject.gradebookng.business.GradebookNgBusinessService - An error occurred updating the assignment
java.lang.NullPointerException
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.updateAssignment(GradebookNgBusinessService.java:1477)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$33fa4029.updateAssignment(<generated>)
	at org.sakaiproject.gradebookng.tool.panels.AddOrEditGradeItemPanel$1.onSubmit(AddOrEditGradeItemPanel.java:99)
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:108)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$1.onSubmit(AjaxFormSubmitBehavior.java:182)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1288)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:952)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:784)`

**Comment by kyleblythe** [comment]
Confirmed.
