### ISSUE TITLE
Exception when TA tries to view gradebook and only has GRADE access to a subset

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1839]
To replicate:

1. have a gradebook with multiple categories
2. give the TA access to an entire category
3. then give them write access to a category but limited to a group, so should look like this:

<img width="485" alt="screen shot 2016-03-01 at 3 29 33 pm" src="https://cloud.githubusercontent.com/assets/608337/13417727/91c93428-dfc2-11e5-9604-96a984b578cb.png">

4. login as the TA
5. Exception:
```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor 'public org.sakaiproject.gradebookng.tool.pages.GradebookPage()'. An exception has been thrown during construction!
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:194)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:67)
	at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:133)
	at org.apache.wicket.core.request.handler.PageProvider.resolvePageInstance(PageProvider.java:268)
	at org.apache.wicket.core.request.handler.PageProvider.getPageInstance(PageProvider.java:166)
	at org.apache.wicket.request.handler.render.PageRenderer.getPage(PageRenderer.java:78)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:279)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:410)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1482)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1167)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1023)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:499)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:271)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:152)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:833)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:471)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:175)
	... 61 more
Caused by: java.lang.SecurityException: User 159f93ad-5e14-485a-adf7-e06e07e835c9 attempted to access grade information for student 4e81e79c-8180-4b6e-b796-8f04d21591b7 without permission in gb 2b609b1a-c003-46d3-87b9-8ce004497e19 using gradebookService.getGradesForStudentsForItem
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getGradesForStudentsForItem(GradebookServiceHibernateImpl.java:1761)
	at sun.reflect.GeneratedMethodAccessor540.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy47.getGradesForStudentsForItem(Unknown Source)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:681)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:556)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$4ca7c616.buildGradeMatrix(<generated>)
	at org.sakaiproject.gradebookng.tool.pages.GradebookPage.<init>(GradebookPage.java:176)
	... 66 more
```

**Comment by payten** [comment]
Feels like a service change, where we could pass in a parameter to suppress security exceptions and only return the grade entries the user has access to.

**Comment by steveswinsburg** [comment]
I thought I had solved this. Grr.

Ok the problem here is that list of studentIds passed to the service is larger than what the TA can see. getGradeableUsers already checks permissions for a TA but maybe it needs a review?

**Comment by payten** [comment]
Yeah, I think the issue is that getGradeableUsers returns all students the TA has permission to grade or view.  The test case I'm seeing fail has the TA able to read all scores in category X for all sections and write for category Y and a subset students.  When we build the the matrix is passes through the super set of the students and hits an exception when one of the readonly students comes up in Category Y. 

So it feels like we need to use the service differently and instead query the groups from the permissions to pass through the student subsets when getting grades for a particular category.  Or modify the service to be quietly swallow those exceptions.

**Comment by steveswinsburg** [comment]
Alternatively the service could not thrown an exception when it sees a passed in user that doesn't match the backend. But it would be interesting to know why those are being passed in in the first place.

**Comment by payten** [comment]
Just hit this same exception opening GBNG with a TA with no rules.  when a TA has no rules/permissions does mean they don't have access to any items?

**Comment by kyleblythe** [comment]
Hi @payten ,

Yeah, I think when a TA doesn't have any rules, they should see a placeholder screen (similar to what displays in the GB when there are no items/students in the site). So a info banner in place of the spreadsheet, stating that they don't have any access permissions for this Gradebook.

**Comment by steveswinsburg** [comment]
Need to also support the TA view, or at least show it as not available in the first instance, because TAs have specific individual permissions. Could possibly masquerade as a specific user but need to ensure it is just for this tool.

**Comment by jeffpasch** [comment]
In the case of TA logging in with no permissions to the GB, display: "You do not have permission to view the gradebook. Please contact your instructor."

In the case where instructor tries to view site as TA, display: "TA view of gradebook cannot be displayed."

**Comment by steveswinsburg** [comment]
- [ ] TA with no permissions
- [ ] roleswap
- [ ] TA user list processing

**Comment by steveswinsburg** [comment]
No permissions and roleswap fix is in PR.

For the bigger issue, because the TA has full access to one category but only a subset in the second, the list passed in is not gradeitem aware, it's the full list, hence the error.

Suppressing the exception makes it work again, however if a TA has grade access to a subset, then they will still be able to view the grades in the rest of the set.

Maybe instead of throwing the stacktrace, we can just remove that user from the list if they are found. This would solve the error and the permission issue.

The other option is to pass in individual lists that are gradeitem aware, only if TA. Performance would be worse and I dont think this will be necessary if we just do the filtering as above.

**Comment by steveswinsburg** [comment]
What I ended up doing was filtering the list. Works well in my testing. This will need some more testing with different combinations

**Comment by kyleblythe** [comment]
This is looking good! Have tried with the following combos

* Grade access to one category for one section/group, and view access to another category for a different section/group
* Grade access to one category for one section/group, and grade access to another category for a different section/group
* Grade access to all categories for one section/group, and grade access to a single category for another section/group

All are working correctly. The lock icons shows up where applicable:

![image](https://cloud.githubusercontent.com/assets/11447474/15756120/dd091d28-28cd-11e6-8139-095942d25929.png)
