### ISSUE TITLE
Need to implement restrictions when using Drop Highest / Drop Lowest / Keep Highest

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2783]
In GBNG, there are currently no restrictions in place re: point values when using Drop Highest / Drop Lowest / Keep Highest.

This means that, currently, you can have items with different total point values being used for these drop/keep calculations. This can therefore lead to incorrect scores being kept/dropped, as the drop/keep rules look to the **score received**, not the score's percentage. Therefore, with drop lowest, a score of 40/50 will be dropped before a score of 50/200.

To remedy this, we should add limitations in GBNG, similar to those which exist in GB1. These include:

**Settings**
There should be a restriction in Settings, preventing users from using drop highest / drop lowest / keep highest in a category that has items with multiple, different point totals in place. The field for a given category should just be greyed out, with alt text explaining that "This category contains items with different point totals. To use [x], all items must have the same point total."

**Add Gradebook Item Lightbox**
When adding a GB item, if a category with drop highest / drop lowest / keep highest is selected and a point total **different** than the established point totals for the category has been entered into the "Points" field, provide a confirmation dialog upon clicking "Create" that warns the user that the established point total will be applied to this item.

**Edit Gradebook Item Lightbox**
The points field should be greyed out. If a different category is selected, the field can become editable.

**Comment by steveswinsburg** [comment]
Discussed 10 JUN 2016. 

When adding a new item, if the category chosen has the drop highest / drop lowest / keep highest settings, just validate on save. Present the message that the points must match existing items that have X score (need to pull this from the assignments in the category and get the highest point value).

When editing, rely on the validation above, don't bother greying out the points just yet.

**Comment by steveswinsburg** [comment]
Done. I didn't add the alt text to the settings page as its already in the instructions :)

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I'm unable to confirm these updates, as I'm getting an error when trying to set up categories & weighting in trunk-mysql - maybe these are related? Created a separate issue for this: #2935.

**Comment by kyleblythe** [comment]
A couple of additional restrictions for feature parity with GB1 in Sakai 10/11, as noted by Molly Kelsey (Notre Dame):

Combinations of Drop Highest / Drop Lowest / Keep Highest:
- If Drop Highest & Keep Highest are implemented at the same time, they must be mutually exclusive. For a given category, only one of these setting can have a non-0 value. Replacing a value with 0 will allow for the other setting to be changed to a non-0 value.
- If Drop Lowest & Keep Highest are implemented at the same time, they must be mutually exclusive. For a given category, only one of these setting can have a non-0 value. Replacing a value with 0 will allow for the other setting to be changed to a non-0 value.

Drop Highest & Drop Lowest can continue to work together, with each having non-0 numbers in place for a given category.

**Comment by steveswinsburg** [comment]
👌 Perfect, will implement. And yes #2935 was an issue when there were no categories, that is fixed.

**Comment by kyleblythe** [comment]
This is looking great, @steveswinsburg !

I was able to produce an error with the drop highest / drop lowest / keep highest. It looks like, if you leave a field blank (which might be fairly common if you enter a value, delete it, then try to tab out), a stacktrace is produced. Ideally, a blank field should automatically get converted to "0" when the user tabs out of the field.

`org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.sakaiproject.gradebookng.tool.panels.SettingsCategoryPanel$8$5@5dec8682 on component [TextField [Component id = categoryDropHighest]] threw an exception
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:250)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1479)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:463)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.handlers.WorksiteHandler.doPost(WorksiteHandler.java:71)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doPost(SkinnableCharonPortal.java:1157)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor847.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	... 55 more
Caused by: java.lang.NullPointerException
	at org.sakaiproject.gradebookng.tool.panels.SettingsCategoryPanel$8$5.onUpdate(SettingsCategoryPanel.java:422)
	at org.apache.wicket.ajax.form.AjaxFormComponentUpdatingBehavior.onEvent(AjaxFormComponentUpdatingBehavior.java:153)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:124)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
	... 59 more`

**Comment by steveswinsburg** [comment]
Ah crap. Sorry, #2996

**Comment by kyleblythe** [comment]
Confirmed! Closing issue.

![image](https://cloud.githubusercontent.com/assets/11447474/16668779/66bfed1e-4460-11e6-9488-bb39278ada9f.png)
