### ISSUE TITLE
"Import From Site" Issue - Cannot import content from GB Classic

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2884]
To replicate:

1. Have a GB set up in an origin site, w/ GB Classic enabled.
2. In the destination site, enable GB Classic _**or**_ GBNG.
3. Attempt to "Import from Site," pulling data from the origin site's GB Classic tool.

Regardless of the existence of GBNG in the destination site, imports from GB Classic don't appear to be working. This might be a bigger blocker issue for 11.0, as folks will need to be able to import content from old GB's into GBNG (or just import GB Classic content into another instance of GB Classic).

What do you think, @steveswinsburg ? Should this be a JIRA, or is it sufficient for this to be recorded in git?

**Comment by steveswinsburg** [comment]
Unless this was broken by work we did, it may not be a blocker. I know we did have to do work in this area, it should be investigated at least.

**Comment by steveswinsburg** [comment]
This looks like it might be related to the logging library change that was done Sakai wide a few weeks back. This should be made into a Jira:
````
23-Jun-2016 11:51:11.974 ERROR [SiteImportThreadf6421649-366a-4edd-976f-568344a888d7] org.sakaiproject.site.tool.SiteAction.transferCopyEntitiesMigrate Error encountered while asking EntityTransfer to transferCopyEntities from: 652e25d7-1e62-4132-82ff-42373ac91179 to: f6421649-366a-4edd-976f-568344a888d7
com.thoughtworks.xstream.converters.ConversionException: null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
class               : org.sakaiproject.component.gradebook.GradebookDefinition
required-type       : org.slf4j.impl.Log4jLoggerAdapter
path                : /org.sakaiproject.component.gradebook.GradebookDefinition/category/org.sakaiproject.tool.gradebook.Category/gradebook/selectedGradeMapping/log
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:63)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.unmarshallField(AnnotationReflectionConverter.java:52)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:169)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:121)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.unmarshallField(AnnotationReflectionConverter.java:52)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:169)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:121)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.unmarshallField(AnnotationReflectionConverter.java:52)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:169)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:121)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:57)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:197)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:169)
	at org.sakaiproject.component.gradebook.VersionedExternalizable$Converter.doUnmarshal(VersionedExternalizable.java:97)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:121)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:117)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategy.unmarshal(ReferenceByXPathMarshallingStrategy.java:29)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:832)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:819)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:767)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:759)
	at org.sakaiproject.component.gradebook.VersionedExternalizable.fromXml(VersionedExternalizable.java:129)
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.transferGradebookDefinitionXml(GradebookServiceHibernateImpl.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy50.transferGradebookDefinitionXml(Unknown Source)
	at org.sakaiproject.tool.gradebook.facades.sakai2impl.GradebookEntityProducer.transferCopyEntities(GradebookEntityProducer.java:111)
	at org.sakaiproject.tool.gradebook.facades.sakai2impl.GradebookEntityProducer.transferCopyEntities(GradebookEntityProducer.java:177)
	at org.sakaiproject.site.tool.SiteAction.transferCopyEntitiesMigrate(SiteAction.java:13753)
	at org.sakaiproject.site.tool.SiteAction.importToolIntoSiteMigrate(SiteAction.java:11894)
	at org.sakaiproject.site.tool.SiteAction.access$300(SiteAction.java:179)
	at org.sakaiproject.site.tool.SiteAction$15.run(SiteAction.java:9480)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:75)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.helpers.NamedLoggerBase.readResolve(NamedLoggerBase.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1104)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1810)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.instantiateUsingSerialization(PureJavaReflectionProvider.java:92)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:49)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:238)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:120)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
	... 60 more

````

**Comment by kyleblythe** [comment]
Created https://jira.sakaiproject.org/browse/SAK-31420

**Comment by steveswinsburg** [comment]
Closing this to get it out of our queue.
