### ISSUE TITLE
Trunk-mysql and qa11-mysql - error when viewing as a student and getTotalPointsPossible returns null

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2912]
As an instructor, can open the grade summary/student review modes for a given student. However, when attempting to view the GB _as_ the student, the following stacktrace is delivered:

`org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [Page class = org.sakaiproject.gradebookng.tool.pages.StudentPage, id = 1, render count = 1]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1696)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3826)
	at org.apache.wicket.Page.onBeforeRender(Page.java:809)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.Component.internalPrepareForRender(Component.java:2194)
	at org.apache.wicket.Page.internalPrepareForRender(Page.java:240)
	at org.apache.wicket.Component.render(Component.java:2283)
	at org.apache.wicket.Page.renderPage(Page.java:1024)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:139)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:229)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1479)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1154)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1010)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:484)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getCourseGrade(GradebookNgBusinessService.java:378)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$20b1009c.getCourseGrade(<generated>)
	at org.sakaiproject.gradebookng.tool.panels.StudentGradeSummaryGradesPanel.onBeforeRender(StudentGradeSummaryGradesPanel.java:150)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	... 64 more`

![image](https://cloud.githubusercontent.com/assets/11447474/16312104/368d15a6-3941-11e6-9e2b-dc1e261c670e.png)

**Comment by kyleblythe** [comment]
From @jonespm - 

> It looks like it's failing on the line in the stack trace

> [1:08]  
> Caused by: java.lang.NullPointerException
>    at  org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getCourseGrade(GradebookNgBusinessService.java:378)

>[1:08]  
>That's here

>[1:08]  
> final CourseGrade courseGrade = this.gradebookService.getCourseGradeForStudent(gradebook.getUid(), studentUuid);
        
>        // handle the special case in the gradebook service where totalPointsPossible = -1
        if(courseGrade.getTotalPointsPossible() == -1)

> [1:08]  
> getCourseGradeForStudent must be returning null for whatever reason and this method is failing

> [1:09]  
> Maybe it's because the student is from a roster on the tests on nightly?

**Comment by jonespm** [comment]
Actually this was introduced in #2141 if getTotalPointsPossible is a null it results in an semi-unusual NPE.

http://stackoverflow.com/a/3352798/3708872

This fixes the immediate problem, unless you didn't intend it to ever be null and wanted a default or something.
https://github.com/sakaiproject/sakai/compare/master...jonespm:GBNG-2912?expand=1

**Comment by kyleblythe** [comment]
Hi @payten & @steveswinsburg ,

The student view is still returning a stacktrace error when attempting to view GBNG:

`org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [Page class = org.sakaiproject.gradebookng.tool.pages.StudentPage, id = 1, render count = 1]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1696)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3826)
	at org.apache.wicket.Page.onBeforeRender(Page.java:809)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.Component.internalPrepareForRender(Component.java:2194)
	at org.apache.wicket.Page.internalPrepareForRender(Page.java:240)
	at org.apache.wicket.Component.render(Component.java:2283)
	at org.apache.wicket.Page.renderPage(Page.java:1024)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:139)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:229)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1479)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1154)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1010)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:484)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getCourseGrade(GradebookNgBusinessService.java:378)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$2654539b.getCourseGrade(<generated>)
	at org.sakaiproject.gradebookng.tool.panels.StudentGradeSummaryGradesPanel.onBeforeRender(StudentGradeSummaryGradesPanel.java:150)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	... 64 more`

**Comment by payten** [comment]
Hi @kyleblythe,  I don't think any of NYU's DEV or SBX environments are updating at the moment after the network changes on the weekend.  I believe we'll need to wait for those to be remedied before we can update to the latest code.  In the meantime, it might be best to test on the Sakai nightly environments.

**Comment by payten** [comment]
Hi @kyleblythe, can you help me replicate this one, annoyingly I'm not seeing it locally.  Was there anything special about the student's grades when this happened?

**Comment by payten** [comment]
I think I found out how to replicate... by ensuring there are no released grade items or having no grade items at all (an empty gradebook).  Will submit a patch for review.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16490173/8a918f5a-3ea6-11e6-9994-31883c610823.png)
