### ISSUE TITLE
Error thrown in student grade summary when ungrouping & grouping items

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3024]
To replicate:

1. Have cat & weighting set up with items in place.
2. Click on student grade summary
3. Ungroup by item.
4. Next, try to group by item again.

You will first receive a browser popup asking if you want to leave the page or not. When you click "Leave," the following error is thrown:

`Unable to find component with id 'categoryGrade' in [WebMarkupContainer [Component id = categoryRow]]
	Expected: 'form:studentGradeSummaryWindow:content:tabs:panel:gradeSummaryTable:categoriesList:0:categoryRow:categoryGrade'.
	Found with similar names: ''
 MarkupStream: [markup = file:/home/sakai/tomcat-deploy/webapps/gradebookng-tool/WEB-INF/classes/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html
<tr wicket:id="categoryRow" class="gb-summary-category-row">
<td>
<a href="javascript:void(0);" class="gb-summary-category-toggle"></a>
<span wicket:id="category" class="gb-summary-category-name"></span>
</td>
<td class="gb-summary-category-grade" wicket:id="categoryGrade"></td>
<td class="gb-summary-category-weight weight-col" wicket:id="categoryWeight"></td>
<td></td>
<td></td>
</tr>, index = 5, current =  '<td class="gb-summary-category-grade" wicket:id="categoryGrade">' (line 0, column 0)]
	at org.apache.wicket.markup.MarkupStream.throwMarkupException(MarkupStream.java:526)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1438)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1557)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1532)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1487)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2529)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1392)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1557)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1532)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1487)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2529)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1392)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1557)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1532)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1487)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2529)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.markup.html.list.ListView.renderItem(ListView.java:584)
	at org.apache.wicket.markup.html.list.ListView.renderChild(ListView.java:573)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onRender(AbstractRepeater.java:101)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1392)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1557)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1532)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1487)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2529)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1392)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1557)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1532)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:689)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:76)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2529)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2359)
	at org.apache.wicket.Component.render(Component.java:2287)
	at org.apache.wicket.ajax.XmlAjaxResponse.writeComponent(XmlAjaxResponse.java:128)
	at org.apache.wicket.ajax.AbstractAjaxResponse.writeComponents(AbstractAjaxResponse.java:218)
	at org.apache.wicket.ajax.AbstractAjaxResponse.writeTo(AbstractAjaxResponse.java:150)
	at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:359)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1481)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:463)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by kyleblythe** [comment]
Confirmed.
