### ISSUE TITLE
Styling / Checkbox Updates for Import Selection Screen

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3274]
Update the styling on the import selection screen to consolidate GB item + comments column into a single, 2-line row w/ zebra-striping to improve ease-of-use.

Additionally, provide highlighting when an item (or comment) is selected for import, using the bootstrap [blue .info contextual class](http://getbootstrap.com/css/#tables-contextual-classes).

Last, provide indented checkboxes for comments columns only when updates are available for those columns (as noted in #3225).

Mockup, with different item import scenarios detailed below:

![updates to import export](https://cloud.githubusercontent.com/assets/11447474/18008764/7ed53984-6b77-11e6-8cbc-0eef1381be52.png)

A) **Updated item scores AND updated comments** - Checkboxes are provided for both the item and its comments. Selecting the item's checkbox will automatically select the associated comments checkbox, though this can be deselected. Clicking only the comments checkbox will select only the comments.

B) **Updated comments WITHOUT updated item scores** - Only the comments-level checkbox is available for selection. The item line lists "No changes," and cannot be selected, as nothing is available to import.

C) **Updated item scores WITHOUT updated comments** - Only the item-level checkbox is available for selection. The comments line lists "No changes," and cannot be selected, as nothing is available to import.

D) **New item column in spreadsheet EITHER with no corresponding comments column in the spreadsheet OR a corresponding comments column in the spreadsheet with no cell contents** - Only the item-level checkbox is available for selection. The comments line lists "No changes," and cannot be selected, as nothing is available to import.

E) **New item column in spreadsheet AND corresponding comments column with content** - Checkboxes are provided for both the item and its comments. Selecting the item's checkbox will automatically select the associated comments checkbox, though this can be deselected. Clicking only the comments checkbox will select only the comments.

**NOTE** - Scenario "E" is the only time in which comments will be marked as "New." At any point, if there are comments that are importable, continue to label them as "Update."

**Comment by steveswinsburg** [comment]
This is ready to go. IMO the confirmation page needs a bit of love.

**Comment by kyleblythe** [comment]
Hmm. Getting the following stacktrace error in UAT:

`org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [Form [Component id = form]]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1696)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3826)
	at org.apache.wicket.markup.html.form.Form.onBeforeRender(Form.java:1784)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3826)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3826)
	at org.apache.wicket.Page.onBeforeRender(Page.java:809)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.Component.internalPrepareForRender(Component.java:2194)
	at org.apache.wicket.Page.internalPrepareForRender(Page.java:240)
	at org.apache.wicket.Component.render(Component.java:2283)
	at org.apache.wicket.Page.renderPage(Page.java:1024)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:139)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:229)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1482)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1154)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1010)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:484)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.handlers.WorksiteHandler.doPost(WorksiteHandler.java:71)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doPost(SkinnableCharonPortal.java:1158)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.sakaiproject.gradebookng.tool.panels.importExport.GradeItemImportSelectionStep$6.populateItem(GradeItemImportSelectionStep.java:296)
	at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:523)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:123)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	... 75 more`

**Comment by kyleblythe** [comment]
course site: https://uathercules.home.nyu.edu/portal/site/b0401bbe-e121-4a1f-a270-3d69a1ace120

[gradebook_export-b0401bbe-e121-4a1f-a270-3d69a1ace120.csv.zip](https://github.com/sakaiproject/sakai/files/501745/gradebook_export-b0401bbe-e121-4a1f-a270-3d69a1ace120.csv.zip)

**Comment by steveswinsburg** [comment]
Ok this is fixed in the above PR. The comment for the last item was missing from the file and the workflow wasn't handling this case.

Note that there is an oddity (maybe) on the confirmation screen. Since comments for NEW Gb Items are imported as part of the corresponding GB Item import, if you selected three NEW GB items to create and one comment item (also new), you will only see the three NEW items on the confirmation screen - ie the comment item will not be shown. I think this page needs a bit of attention - we could possibly collapse the three tables and then just show all of the data with a bit of work, but it might be lower priority as it's all correct in the end.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/19084126/39c8f9d6-8a33-11e6-9a65-0b7aaff254a7.png)

Agreed re: the confirmation screen. Can create a separate issue, and close this one out for now. Nice!
