### ISSUE TITLE
NPE on getSortOrder in GradebookNgBusinessService

### ISSUE THREAD

**Issue by ottenhoff** [sakaiproject/sakai#3566]
```
70 Caused by: java.lang.NullPointerException
71 	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getAssignmentSortOrder(GradebookNgBusinessService.java:1370)
72 	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
73 	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
74 	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
75 	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$4c3dddba.getAssignmentSortOrder(<generated>)
76 	at org.sakaiproject.gradebookng.tool.panels.AssignmentColumnHeaderPanel$5.onClick(AssignmentColumnHeaderPanel.java:279)
77 	at org.apache.wicket.markup.html.link.Link.onLinkClicked(Link.java:190)
78 	... 61 more
```

**Comment by ottenhoff** [comment]
PR: https://github.com/sakaiproject/sakai/pull/3567

**Comment by payten** [comment]
Thanks @ottenhoff.  Will merge ASAP.  Just wondering how to replicate this one?  I think I can poke the DB to remove the sortOrder value, but wondering if there's a way to do that through the interface? Or is it a legacy data thing that we missed?

Thanks again.

**Comment by payten** [comment]
Oh, I got it.  To replicate:
1. Add an external gradebook item via assignments or samigo.
2. In GradebookNG, go to the menu and click "Move Left" or "Move Right"
3. Error

**Comment by ottenhoff** [comment]
Yup we can patch GradebookExternalAssessmentServiceImpl  ... feel free to modify this PR or I can look tomorrow

**Comment by payten** [comment]
Hi @ottenhoff, 

I had a quick go, but soon realised that there's some voodoo going on in that `GradebookExternalAssessmentServiceImpl` class!  Here's what I ended up with, but there are two different implementations of `addExternalAssessment` with slightly different signatures?  Otherwise this seems to do the needful:

```
diff --git a/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java b/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
index dab0cbc..ccdf4b0 100644
--- a/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
+++ b/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
@@ -198,6 +198,10 @@ public class GradebookExternalAssessmentServiceImpl extends BaseHibernateManager
                                        throw new ConflictingExternalIdException("An external assessment with that ID already exists in gradebook uid=" + gradebookUid);
                                }
 
+                               Integer maxSortOrder = (Integer)session.createQuery(
+                                       "select max(asn.sortOrder) from Assignment as asn where asn.gradebook.uid=?").
+                                       setString(0, gradebookUid).uniqueResult();
+
                                // Get the gradebook
                                Gradebook gradebook = getGradebook(gradebookUid);
 
@@ -212,6 +216,8 @@ public class GradebookExternalAssessmentServiceImpl extends BaseHibernateManager
                 asn.setReleased(true);
         asn.setUngraded(false);
 
+                               asn.setSortOrder(maxSortOrder == null ? 0 : maxSortOrder + 1);
+
                 session.save(asn);
                                return null;
                        }
@@ -784,6 +790,10 @@ public class GradebookExternalAssessmentServiceImpl extends BaseHibernateManager
                                    }
                                }
 
+                               Integer maxSortOrder = (Integer)session.createQuery(
+                                       "select max(asn.sortOrder) from Assignment as asn where asn.gradebook.uid=?").
+                                       setString(0, gradebookUid).uniqueResult();
+
                                // Create the external assignment
                                Assignment asn = new Assignment(gradebook, title, points, dueDate);
                                asn.setExternallyMaintained(true);
@@ -801,6 +811,8 @@ public class GradebookExternalAssessmentServiceImpl extends BaseHibernateManager
                                else
                                        asn.setUngraded(false);
 
+                               asn.setSortOrder(maxSortOrder == null ? 0 : maxSortOrder + 1);
+
                                session.save(asn);
                                return null;
                        }
```

**Comment by ottenhoff** [comment]
Yeah, I'm in over my head here. I don't know the reason for the two method signatures.

**Comment by kyleblythe** [comment]
Confirmed in trunk. Closing issue.
