### ISSUE TITLE
Custom role without gb permissions will receive ugly stack trace on home page instead of access denied error

### ISSUE THREAD

**Issue by ottenhoff** [sakaiproject/sakai#3804]
To replicate:

1) Add a custom role to existing site called "Course Builder"
2) Assign some permissions to build content but dont assign any GB permissions
3) Assign a user to the new "Course Builder" role
4) Become User 
5) Go to the site and go to Gradebook tool

`
Caused by: java.lang.SecurityException: You do not have permission to perform this operation 
at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getCategoryDefinitions(GradebookServiceHibernateImpl.java:2574) 
.
.
.
at org.sakaiproject.gradebookng.tool.pages.GradebookPage.getUiSettings(GradebookPage.java:729) 
at org.sakaiproject.gradebookng.tool.pages.GradebookPage.<init>(GradebookPage.java:193) 
`

**Comment by steveswinsburg** [comment]
Good catch, will correct this exception handling to take the user to the access denied page.

**Comment by steveswinsburg** [comment]
PR sent

**Comment by steveswinsburg** [comment]
Ready to test

**Comment by kyleblythe** [comment]
Confirmed in trunk:

![image](https://cloud.githubusercontent.com/assets/11447474/23769737/5a70e826-04de-11e7-818c-fc5c84dca00d.png)
